### ISSUE TITLE
Algorithm - Quick sort 아주 사소한 줄바꿈, bold

### ISSUE THREAD

**Issue by kndnwn49090** [GimunLee/tech-refrigerator#10]
https://github.com/GimunLee/tech-refrigerator/blob/master/Algorithm/%ED%80%B5%20%EC%A0%95%EB%A0%AC%20(Quick%20Sort).md#%EC%8B%9C%EA%B0%84%EB%B3%B5%EC%9E%A1%EB%8F%84--%EA%B3%B5%EA%B0%84%EB%B3%B5%EC%9E%A1%EB%8F%84

그림과 글 사이에 줄바꿈이 안되어있어 오류

<img width="834" alt="스크린샷 2019-12-18 오후 4 30 32" src="https://user-images.githubusercontent.com/26381225/71065127-ea2e8000-21b3-11ea-98cc-f6e5126a81a0.png">

같은 글에 bold 오류

<img width="1036" alt="스크린샷 2019-12-18 오후 4 35 47" src="https://user-images.githubusercontent.com/26381225/71065391-80fb3c80-21b4-11ea-949d-fbef26a36f8e.png">

**Comment by GimunLee** [comment]
감사합니다. 😄 수정하겠습니다. 👍
