### ISSUE TITLE
GC전 Java 메모리관한 내용 추가 부탁

### ISSUE THREAD

**Issue by ssungwxx** [GimunLee/tech-refrigerator#5]
GC에 메모리영역에 대한 이야기가 많이 나오는데 해당 부분에 대한 자세한 내용이 없어 아쉽습니다.

GC전에 메모리에 관한 이야기가 들어가면 좋을거 같습니다.

**Comment by GimunLee** [comment]
의견 감사합니다. 추가해보겠습니다 😄
