### ISSUE TITLE
Algorithm - Selection sort 아주 사소한 bold.

### ISSUE THREAD

**Issue by kndnwn49090** [GimunLee/tech-refrigerator#9]
<img width="122" alt="스크린샷 2019-12-18 오후 3 44 28" src="https://user-images.githubusercontent.com/26381225/71062325-8ef98f00-21ad-11ea-9811-5ccc5ff0ec91.png">

https://github.com/GimunLee/tech-refrigerator/blob/master/Algorithm/%EC%84%A0%ED%83%9D%20%EC%A0%95%EB%A0%AC%20(Selection%20Sort).md#%EC%8B%9C%EA%B0%84%EB%B3%B5%EC%9E%A1%EB%8F%84--%EA%B3%B5%EA%B0%84%EB%B3%B5%EC%9E%A1%EB%8F%84

<변경전>
`  - 주어진 배열 안에서 교환(swap)을 통해, 정렬이 수행되므로 **O(n)**입니다.`
 - 주어진 배열 안에서 교환(swap)을 통해, 정렬이 수행되므로 **O(n)**입니다.

<변경 요망>
`  - 주어진 배열 안에서 교환(swap)을 통해, 정렬이 수행되므로 **O(n)** 입니다.`
 - 주어진 배열 안에서 교환(swap)을 통해, 정렬이 수행되므로 **O(n)** 입니다.

**Comment by GimunLee** [comment]
감사합니다. 😄 수정하겠습니다. 👍
